image: python:3.11.2
pipelines:
  branches:
    master:
      - step:
          name: "code deploying"
          script:
            - ssh ubuntu@157.241.54.34 /home/ubuntu/saleh-dashboard-fr/devCdScript.sh

